name: 'Auto code generation experiment (3): Create draft release'

on:
  workflow_call:

jobs:
  create_draft_release:
    name: Create draft release
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create draft release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.pull_request.title }}
          release_name: Release v${{ github.event.pull_request.title }}
          body: |
            ${{ github.event.pull_request.body }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  delete_working_branch:
    name: Delete working branch
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: write
    steps:
      - name: Delete working branch
        uses: actions/github-script@v6.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const ownerAndRepoName = context.payload.repository.full_name.split('/');
            const owner = ownerAndRepoName[0];
            const repo = ownerAndRepoName[1];
            const ref = `heads/${context.payload.pull_request.head.ref}`;
            const res = await github.git.deleteRef({
              owner,
              repo,
              ref,
            });
            console.log(res);
