name: 'Auto code generation experiment (2): Generate code'

on:
  workflow_call:

jobs:
  generate_code:
    name: Generate code and push them
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{ github.head_ref }}

      - name: Update version file
        run: |
          echo $TARGET_VERSION > version.txt
        env:
          TARGET_VERSION: ${{ github.event.pull_request.title }}

      - name: Create a commit
        run: |
          git branch
          git config user.name "Auto code generator"
          git add version.txt
          git commit -m "Generate code for ${TARGET_VERSION}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
