name: 'Experiment: Inspect Dependabot'

on:
  pull_request:
    types: ["opened", "synchronize", "reopened", "edited"]

jobs:
  main:
    name: Experiment Dependabot's trigger
    if: ${{ github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'dependencies') }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Debug: Show GitHub context'
        run: |
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}

      - name: Comment to the pull request with GITHUB_TOKEN
        uses: actions/github-script@v6.4.0
        id: add-comment
        env:
          BODY: ${{ github.event.action }}
        with:
          script: |
            const { BODY } = process.env
            return github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: BODY,
            });
          github-token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Show the result
        env:
          RETURN_CONTEXT: ${{ toJson(steps.add-comment.outputs) }}
        run: |
          echo "$RETURN_CONTEXT"

      - name: Confirm Dependabot secrets
        env:
          DEPENDABOT_SECRET: ${{ secrets.DEPENDABOT_SECRET }}
        run: |
          echo "$DEPENDABOT_SECRET"
