name: 'Webapp deployment experiment: Test Web App'

on:
  workflow_call:
    inputs:
      dotnet_version:
        description: .NET version
        required: true
        type: string

jobs:
  test:
    runs-on: windows-latest
    env:
      DOTNET_VERSION: ${{ inputs.dotnet_version }}
      WORKING_DIR: src/webapp
    outputs:
      webapp_archived_app_name: ${{ env.WEBAPP_ARCHIVED_APP_NAME }}
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore packages from cache
      uses: actions/cache@v3.0.11
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    # Run dotnet build and publish
    - name: dotnet build and publish
      run: |
        dotnet restore
        dotnet test
      working-directory: ${{ env.WORKING_DIR }}
