name: 'Webapp deployment experiment: Build Web App'

on:
  workflow_call:
    inputs:
      dotnet_version:
        description: .NET version
        required: true
        type: string
    outputs:
      webapp_archived_app_name:
        description: A archived app name for Azure Web app
        value: ${{ jobs.build.outputs.webapp_archived_app_name }}

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_VERSION: ${{ inputs.dotnet_version }}
      WORKING_DIR: src/webapp
      AZURE_WEBAPP_PACKAGE_PATH: ${{ github.workspace }}/outputs
      WEBAPP_ARCHIVED_APP_NAME: .net-app
    outputs:
      webapp_archived_app_name: ${{ env.WEBAPP_ARCHIVED_APP_NAME }}
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core SDK ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore packages from cache
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    # Run dotnet build and publish
    - name: dotnet build and publish
      run: |
        dotnet restore
        dotnet build --configuration Release
        dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
      working-directory: ${{ env.WORKING_DIR }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.WEBAPP_ARCHIVED_APP_NAME }}
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
